#!/bin/ash

DIR=$(dirname $0)

OPTS="$OPTS -Djava.util.logging.config.file=${DIR}/logging.properties"

if [ -n "$TIMEZONE" ]
then
    OPTS="$OPTS -Duser.timezone=$TIMEZONE"
fi

if [ -n "$RUNJDWP" ]
then
    OPTS="$OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=$RUNJDWP,server=y,suspend=y"
fi

if [ -n "$PREFER_IPv6_ADDRESSES" ]
then
    OPTS="$OPTS -Djava.net.preferIPv6Addresses=true"
fi

OPTS="$OPTS -cp $(echo $(ls $DIR/lib/*.jar)|sed "s/ /:/g")"

exec java $OPTS uk.trainwatch.kernel.Main $@
