// Extract all temperature parameters from a grib file

gribName = "/home/peter/gfs.grib";

log "Opening grib " + gribName;
grib = openGrib(gribName);

log "Generating index";
t = table();
row = t.newHeader();
row.newCell( "Index" );
row.newCell( "prodId" );
row.newCell( "catId" );
row.newCell( "nameId" );
row.newCell( "Cat" );
row.newCell( "Name" );
row.newCell( "Unit" );
row.newCell( "Product" );

log "Index of available products within "+gribName+"\n" + t;
