// Display map with temperature data overlaid as text
job "plot1";
run as "test";
{
    gribName = "/home/peter/gfs.grib";

    log "Opening grib " + gribName;
    grib = openGrib(gribName);

    // Temperature at Ground/Water surface
    temp = findGribParameter(grib,0,0,0,1,0);

    layers = new tileLayerSet();
    layers.add( new tileGridLayer() );
    layers.add( new baseTileLayer("Open Street Map") );
    
    image = createImage(1024,1024);
    renderMap(image,6,30,18,layers);
    writeImage(image,"uk-temp.png");

}
