// Tests the netcdf module
//
// Test getting a specific grid from a grib file
//

    map = new mapContent();

    worldSource = getFeatureSource( "/usr/local/shape/50m_cultural/ne_50m_admin_0_countries.shp" );

    // Green land
    stroke = createStroke( "black", 1);
    fill = createFill( "green", 0.5 );
    //style = createPolygonStyle( stroke, fill );
    style = createLineStyle( stroke );

    layer = new featureLayer( worldSource, style );
    map.addLayer( layer );

log "Opening gfs";

try( r = new cdfReader( "/home/peter/gfs.grib" ) ) {
    temp = cdfGetGrid( r, "Temperature_surface" );
    tempStyle = createGreyscaleStyle(  );

    tempLayer = new gridCoverageLayer( temp, tempStyle );
    //tempLayer = new gridCoverageLayer( correctGridCoverageHemisphere(temp,true), tempStyle );
    map.addLayer( tempLayer );

//    tempLayer = new gridCoverageLayer( correctGridCoverageHemisphere(temp,false), tempStyle );
//    map.addLayer( tempLayer );
}

    layer = new featureLayer( worldSource, style );
    map.addLayer( layer );

    //setMapBounds( map, -32, 33, 70, 82 );
    setMapBounds( map, -180, -90, 180, 90 );
    //setMapBounds( map, 180, -90, 360+180, 90 );
    size = getMapBounds(map,700);

    renderMapContent( "cdf5.png", map, "white", "black", size);
