//
// Tests renderMapContent with a SVG File
//
// Generates a simple vector map of the UK
//
// Note: This requires the ne_50m_admin_0_countries.dbf from 50m-cultural-vectors
//
// http://www.naturalearthdata.com/downloads/50m-cultural-vectors/
//

worldSource = getFeatureSource( "/usr/local/shape/50m_cultural/ne_50m_admin_0_countries.shp" );

// Green land
stroke = createStroke( "black", 1);
fill = createFill( "green", 0.5 );
style = createPolygonStyle( stroke, fill );
layer = new featureLayer( worldSource, style );

map = new mapContent();
map.addLayer( layer );

setMapBounds( map, -11, 62, 4, 48 );

size = getMapBounds(map,700);

renderMapContent( "render3.svg", map, "white", "black", size);
