// Generates a simple vector map of the world
//
// Note: This requires the ne_50m_admin_0_countries.dbf from 50m-cultural-vectors
//
// http://www.naturalearthdata.com/downloads/50m-cultural-vectors/
//

worldSource = getFeatureSource( "/usr/local/shape/50m_cultural/ne_50m_admin_0_countries.shp" );

layer = new featureLayer( worldSource );

map = new mapContent( "World Map 1" );
map.addLayer( layer );

// createImage will distort hence use createMapImage as height is then relative to the width & viewport
//image = createImage(700,700);
image = createMapImage(map,700);

log image.getWidth();
log image.getHeight();

renderMapContent(image,map, "white", "black");

writeImage(image,"world1.png");
